version: "3.7"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - db-data:/foo # use volumes to store DB data into multiple places
    ports:
      - "5433:5432"

  web:
    build: . # use docker file from root
    # ports:
    #   - "4001:3000"
    environment:
      - NODE_ENV=production
      # https://docs.docker.com/compose/environment-variables/
      - POSTGRES_PRODUCTION_USERNAME=${POSTGRES_PRODUCTION_USERNAME}
      - POSTGRES_PRODUCTION_PASSWORD=${POSTGRES_PRODUCTION_PASSWORD}
      - POSTGRES_PRODUCTION_DB=${POSTGRES_PRODUCTION_DB}
      - POSTGRES_PRODUCTION_HOST=${POSTGRES_PRODUCTION_HOST}
      - POSTGRES_PRODUCTION_PORT=5432
      - APP_NO=1
    restart: always # restart on crash
    links:
      - db

  nginx:
    build:
      context: ./nginx/
      dockerfile: nginx.Dockerfile
    depends_on:
      - web
    ports:
      - "5100:5100"
    restart: always

volumes:
  db-data:
